# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'D-Transform' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for D-Transform
  pod 'RealmSwift'

  target 'D-TransformTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'D-TransformUITests' do
    # Pods for testing
  end

end
